---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: tcpretransmetric-certs
  labels:
    k8s-app: tcpretransmetric-daemon
  name: tcpretransmetric-daemon
  namespace: openshift-bpftest
spec:
  selector:
    k8s-app: tcpretransmetric-daemon
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: tcpretransmetric-daemon-metrics
    port: 9905
    protocol: TCP
    targetPort: 9905
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: tcpretransmetric-daemon
  name: tcpretransmetric-daemon
  namespace: openshift-bpftest
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      port: tcpretransmetric-daemon-metrics
      scheme: https
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        serverName: tcpretransmetric-daemon.openshift-bpftest.svc
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - openshift-bpftest
  selector:
    matchLabels:
      k8s-app: tcpretransmetric-daemon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: openshift-bpftest
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
  name: prometheus-k8s
  namespace: openshift-bpftest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-bpftest-operator
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-bpftest-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-bpftest-operator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: openshift-bpftest
